### ISSUE TITLE
Config?

### ISSUE THREAD

**Issue by Mxdi** [sphexator/Discord.me-bump-bot#2]
How the hell do you even get the api key ? Let alone what api key? And maybe provide exmaples regarding how to get any of the information you want stored in the config?

**Comment by silent** [comment]
It shows where to get the API key lol. 
![image](https://user-images.githubusercontent.com/36117192/63379714-7f328100-c35a-11e9-8b18-b6e2d6179cb4.png)
![image](https://user-images.githubusercontent.com/36117192/63379720-8194db00-c35a-11e9-9c5f-71ede426aee3.png)

**Comment by Mxdi** [comment]
Does this bump bot even still work ? How often does it check to bump??

**Comment by silent** [comment]
Tbh, I am just waiting for a response. I opened an issue yesterday lol.

**Comment by Mxdi** [comment]
lol i didnt know i had to pay to use the captcha solver... dont think ill be using this.

**Comment by Mxdi** [comment]
Good luck with getting support for your issue though... Thanks for responding.

**Comment by sphexator** [comment]
Hello

This is currently a WIP project and is currently not in a functional state.

The config is quite self-explainatory aside from 2 fields which is the profile path and server ids, how to get em and if they're required. The profile path is not required, but the server ids are. You get the server ids by inspecting elements when you're on discord.me and on their dashboard, check the servers you have on your dashboard and there should be a field which has their server id (or servereuid). 



> Does this bump bot even still work ? How often does it check to bump??

Not currently in a functional state, but as discord.me has scheduled bump windows every 6 hours in UTC, its scheduled to run the bump task every 6hr by the clock (6 12 6 12) in UTC.

 

> pay to use the captcha solver

Unless you want to run one for a day or two till it stops working and wont work ever again, you'll likely not find a captcha solver that doesn't cost money.
